Repository solidtoken/SpecFlow.DependencyInjection, pull requests merged in 2022-05, with the labels that each got.

#74 real DI scoping
  SpecFlow.DependencyInjection/DependencyInjectionPlugin.cs
  SpecFlow.DependencyInjection/DependencyInjectionTestObjectResolver.cs
  SpecFlow.DependencyInjection/IServiceCollectionFinder.cs
  SpecFlow.DependencyInjection/ScenarioDependenciesAttribute.cs
  SpecFlow.DependencyInjection/ServiceCollectionFinder.cs
Labels: enhancement

#84 Fix missing BindMappings for ScenarioContext
  SpecFlow.DependencyInjection.Tests/ScenarioContextDisposal.feature
  SpecFlow.DependencyInjection.Tests/ScenarioContextDisposalSteps.cs
  SpecFlow.DependencyInjection/DependencyInjectionPlugin.cs
  SpecFlow.DependencyInjection/DependencyInjectionTestObjectResolver.cs
  SpecFlow.DependencyInjection/ScenarioDependenciesAttribute.cs
  SpecFlow.DependencyInjection/ServiceCollectionFinder.cs
Labels: bug

#85 Fix missing IUnitTestRuntimeProvider
  SpecFlow.DependencyInjection.Tests/UnitTestRuntimeProvider.feature
  SpecFlow.DependencyInjection.Tests/UnitTestRuntimeProviderSteps.cs
  SpecFlow.DependencyInjection/DependencyInjectionPlugin.cs
Labels: bug

#87 Add ISpecFlowOutputHelper test
  SpecFlow.DependencyInjection.Tests/ISpecFlowOutputHelper.feature
  SpecFlow.DependencyInjection.Tests/ISpecFlowOutputHelperSteps.cs
  SpecFlow.DependencyInjection.Tests/TestDependencies.cs
Labels: chore
